import{S as h}from"./assets/vendor-C8mLK4Kr.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const w=[{selector:".profile-swiper",slideClass:"profile-swiper-slide",wrapperClass:"profile-swiper-wrapper",paginationItemSelector:".profile-pagination-item",slidesPerViewMobile:1.2},{selector:".how-swiper",slideClass:"how-swiper-slide",wrapperClass:"how-swiper-wrapper",paginationItemSelector:".how-pagination-item",slidesPerViewMobile:1},{selector:".join-swiper",slideClass:"join-swiper-slide",wrapperClass:"join-swiper-wrapper",paginationItemSelector:".join-pagination-item",slidesPerViewMobile:1.2}],l={};function p(){const s=window.innerWidth;w.forEach(o=>{if(!document.querySelector(o.selector))return;const n=o.selector;if(l[n]&&(l[n].destroy(!0,!0),delete l[n],g(o.paginationItemSelector)),s<1439){const e=new h(n,{slidesPerView:o.slidesPerViewMobile,spaceBetween:10,loop:!0,slideClass:o.slideClass,wrapperClass:o.wrapperClass,direction:"horizontal",on:{init:function(){d(o.paginationItemSelector,this.realIndex)},slideChange:function(){d(o.paginationItemSelector,this.realIndex)}}});l[n]=e,document.querySelectorAll(o.paginationItemSelector).forEach((i,c)=>{i.addEventListener("click",()=>{e.slideToLoop(c)})})}})}function d(s,o){document.querySelectorAll(s).forEach((n,e)=>{n.classList.toggle("active",e===o)})}function g(s){document.querySelectorAll(s).forEach(r=>r.classList.remove("active"))}document.addEventListener("DOMContentLoaded",p);window.addEventListener("resize",p);document.addEventListener("DOMContentLoaded",()=>{const s=document.querySelector(".menu-button"),o=s.querySelector(".icon"),r=document.querySelector(".modal"),n=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const i=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M3 12H21M3 6H21M3 18H21" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
</svg>
    `,c=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M3 3L12 12L21 21M3 21L21 3" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
</svg>
    `;s.addEventListener("click",()=>{t=!t,o.innerHTML=t?c:i,t?u():a()}),n.forEach(f=>f.addEventListener("click",()=>{a(),o.innerHTML=i,t=!1})),window.addEventListener("scroll",m);function u(){r.style.display="block"}function a(){r.style.display="none"}function m(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function s(){const n=document.getElementById("site-header");return n?n.offsetHeight:0}function o(n){const e=document.getElementById(n);if(!e)return;const t=s(),i=e.getBoundingClientRect().top+window.pageYOffset-t;window.scrollTo({top:i,behavior:"smooth"})}if(location.pathname.endsWith("index.html")||location.pathname==="/"||location.pathname==="/index"){document.querySelectorAll('a[href*="#"]').forEach(e=>{e.addEventListener("click",t=>{const i=e.getAttribute("href"),c=i.split("#")[1];(i.startsWith("#")||i.startsWith("index.html#")||i.startsWith("/index.html#"))&&(t.preventDefault(),o(c))})});const n=window.location.hash;if(n){const e=n.substring(1),t=()=>{document.getElementById(e)?o(e):requestAnimationFrame(t)};setTimeout(t,100)}}});document.addEventListener("DOMContentLoaded",function(){const s=document.getElementById("cookie-popup"),o=document.getElementById("accept-cookies"),r=document.getElementById("decline-cookies");localStorage.getItem("cookiesAccepted")||(s.style.display="block"),o.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","yes"),s.style.display="none"}),r.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","no"),s.style.display="none"})});
//# sourceMappingURL=index.js.map
