import{S as w}from"./assets/vendor-C8mLK4Kr.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const g=[{selector:".profile-swiper",slideClass:"profile-swiper-slide",wrapperClass:"profile-swiper-wrapper",paginationItemSelector:".profile-pagination-item",slidesPerViewMobile:1.2},{selector:".how-swiper",slideClass:"how-swiper-slide",wrapperClass:"how-swiper-wrapper",paginationItemSelector:".how-pagination-item",slidesPerViewMobile:1},{selector:".join-swiper",slideClass:"join-swiper-slide",wrapperClass:"join-swiper-wrapper",paginationItemSelector:".join-pagination-item",slidesPerViewMobile:1.2}],l={};function u(){const i=window.innerWidth;g.forEach(t=>{if(!document.querySelector(t.selector))return;const n=t.selector;if(l[n]&&(l[n].destroy(!0,!0),delete l[n],y(t.paginationItemSelector)),i<1439){const e=new w(n,{slidesPerView:t.slidesPerViewMobile,spaceBetween:10,loop:!0,slideClass:t.slideClass,wrapperClass:t.wrapperClass,direction:"horizontal",on:{init:function(){d(t.paginationItemSelector,this.realIndex)},slideChange:function(){d(t.paginationItemSelector,this.realIndex)}}});l[n]=e,document.querySelectorAll(t.paginationItemSelector).forEach((s,c)=>{s.addEventListener("click",()=>{e.slideToLoop(c)})})}})}function d(i,t){document.querySelectorAll(i).forEach((n,e)=>{n.classList.toggle("active",e===t)})}function y(i){document.querySelectorAll(i).forEach(r=>r.classList.remove("active"))}document.addEventListener("DOMContentLoaded",u);window.addEventListener("resize",u);document.addEventListener("DOMContentLoaded",()=>{const i=document.querySelector(".menu-button"),t=i.querySelector(".icon"),r=document.querySelector(".modal"),n=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let o=!1;const s=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M3 12H21M3 6H21M3 18H21" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
</svg>
    `,c=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M3 3L12 12L21 21M3 21L21 3" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
</svg>
    `;i.addEventListener("click",()=>{o=!o,t.innerHTML=o?c:s,o?m():a()}),n.forEach(h=>h.addEventListener("click",()=>{a(),t.innerHTML=s,o=!1})),window.addEventListener("scroll",f);function m(){r.style.display="block"}function a(){r.style.display="none"}function f(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function i(){const n=document.getElementById("site-header");return n?n.offsetHeight:0}function t(n){const e=document.getElementById(n);if(!e)return;const o=i(),s=e.getBoundingClientRect().top+window.pageYOffset-o;window.scrollTo({top:s,behavior:"smooth"})}if(location.pathname.endsWith("index.html")||location.pathname==="/"||location.pathname==="/index"){document.querySelectorAll('a[href*="#"]').forEach(e=>{e.addEventListener("click",o=>{const s=e.getAttribute("href"),c=s.split("#")[1];(s.startsWith("#")||s.startsWith("index.html#")||s.startsWith("/index.html#"))&&(o.preventDefault(),t(c))})});const n=window.location.hash;if(n){const e=n.substring(1),o=()=>{document.getElementById(e)?t(e):requestAnimationFrame(o)};setTimeout(o,100)}}});document.addEventListener("DOMContentLoaded",function(){const i=document.getElementById("cookie-popup"),t=document.getElementById("accept-cookies"),r=document.getElementById("decline-cookies");localStorage.getItem("cookiesAccepted")||(i.style.display="block"),t.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","yes"),i.style.display="none"}),r.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","no"),i.style.display="none"})});const p=document.querySelectorAll(".navigation-item");p.forEach(i=>{i.addEventListener("click",function(t){t.preventDefault(),p.forEach(r=>r.classList.remove("active")),this.classList.add("active")})});
//# sourceMappingURL=index.js.map
